"""initial commit: added users and user_identities tables

Revision ID: d038dffaf840
Revises: 
Create Date: 2026-01-15 20:22:46.555152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd038dffaf840'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('email_verification_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('id')
    )
    op.create_index('idx_users_active_created', 'users', ['is_active', 'created_at'], unique=False)
    op.create_table('user_identities',
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('provider_user_id', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=1024), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('provider', 'provider_user_id', name='uq_identities_provider_user')
    )
    op.create_index('idx_identities_provider_lookup', 'user_identities', ['provider', 'provider_user_id'], unique=False)
    op.create_index('idx_identities_user_id', 'user_identities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_identities_user_id', table_name='user_identities')
    op.drop_index('idx_identities_provider_lookup', table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index('idx_users_active_created', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
